### ISSUE TITLE
System.InvalidOperationException - won't run.

### ISSUE THREAD

**Issue by Noctis-** [Kyome22/RunCat_for_windows#19]
```
System.InvalidOperationException
  HResult=0x80131509
  Message=Cannot load Counter Name data because an invalid index '' was read from the registry.
  Source=System.Diagnostics.PerformanceCounter
  StackTrace:
   at System.Diagnostics.PerformanceCounterLib.GetStringTable(Boolean isHelp)
   at System.Diagnostics.PerformanceCounterLib.get_NameTable()
   at System.Diagnostics.PerformanceCounterLib.get_CategoryTable()
   at System.Diagnostics.PerformanceCounterLib.CounterExists(String category, String counter, Boolean& categoryExists)
   at System.Diagnostics.PerformanceCounterLib.CounterExists(String machine, String category, String counter)
   at System.Diagnostics.PerformanceCounter.InitializeImpl()
   at System.Diagnostics.PerformanceCounter..ctor(String categoryName, String counterName, String instanceName, Boolean readOnly)
   at System.Diagnostics.PerformanceCounter..ctor(String categoryName, String counterName, String instanceName)
   at RunCat.RunCatApplicationContext..ctor() in D:\Coding\C#\RunCat_for_windows-1.8\RunCat\Program.cs:line 60
   at RunCat.Program.Main() in D:\Coding\C#\RunCat_for_windows-1.8\RunCat\Program.cs:line 34
```

is this Cpu dependant ?

**Comment by Noctis-** [comment]
Not an issue with the code ... apparently win 10 can get out of whack with it's performance counters: 

![image](https://user-images.githubusercontent.com/6160139/122515235-7b541080-d050-11eb-8b1d-3bdc19c67079.png)

following the steps [in this link](https://social.technet.microsoft.com/Forums/azure/en-US/9b01e1a6-d872-4f28-9280-f35d6ca02a9f/lodctr-r-error-code-2?forum=w7itprogeneral) fixed it up
